sources:
  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders
        freshness: 
          error_after:
            count: 2
            period: day
          warn_after:
            count: 1
            period: day
        loaded_at_field: _ETL_loaded_at
        
      - name: customers
