sources:
  - name: stripe
    database: til_portfolio_projects
    schema: stripe
    tables:
      - name: payment
  - name: jaffle_shop
    database: til_portfolio_projects
    schema: jaffle_shop
    tables:
      - name: orders