sources:
  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
        loaded_at_field: _batched_at
        freshness:
          warn_after:
            count: 12
            period: hour
          error_after: 
            count: 24
            period: hour

  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders
        freshness:
          error_after:
            count: 2
            period: day
          warn_after:
            count: 1
            period: day
        loaded_at_field: _ETL_loaded_at

      - name: customers
